spring.application.name=lms-api

# Local Default Database Configuration (Will be overridden by docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db?options=-c%20timezone=UTC
spring.datasource.username=lms_user
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ Local Default Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest