-- Створення таблиці категорій
CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            name VARCHAR(255) NOT NULL,
                            PRIMARY KEY (id),
                            CONSTRAINT uk_category_name UNIQUE (name)
);

-- Створення таблиці користувачів
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
                       PRIMARY KEY (id),
                       CONSTRAINT uk_user_email UNIQUE (email)
);

-- Створення таблиці курсів
CREATE TABLE courses (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         title VARCHAR(255) NOT NULL,
                         instructor VARCHAR(255) NOT NULL,
                         duration_hours INTEGER NOT NULL,
                         category_id BIGINT,
                         PRIMARY KEY (id),
                         CONSTRAINT fk_courses_category FOREIGN KEY (category_id) REFERENCES categories(id)
);